import { Head, Link, router } from '@inertiajs/react';
import { Activity, ArrowUpRight, Ban, CheckCircle2, ChevronRight, Copy, ExternalLink, Github, KeyRound, LayoutDashboard, MoreHorizontal, Search, ShieldCheck, SlidersHorizontal, Users, type LucideIcon } from 'lucide-react';
import { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import DashboardLayout from '@/layouts/dashboard-layout';
import { cn } from '@/lib/utils';

type Metric = { users: number; mods: number; api_keys: number; requests_today: number };
type AdminUser = { id: number; name: string; username: string; email: string; avatar: string; is_admin: boolean; is_suspended: boolean; owned_mods_count: number; api_keys_count: number; created_at: string };
type ApiKey = { id: number; name: string; prefix: string; user: string; scopes: string[]; last_used_at: string | null; expires_at: string | null };
type ActivityItem = { id: number; method: string; path: string; status_code: number; user: string; created_at: string };
type AdminMod = { id: number; name: string; slug: string; owner: string; pages_count: number; updated_at: string; is_suspended: boolean; github_connected: boolean; activity: { title: string; updated_at: string }[] };

export default function Admin({ metrics, users, keys, activity, mods }: { metrics: Metric; users: AdminUser[]; keys: ApiKey[]; activity: ActivityItem[]; mods: AdminMod[] }) {
  const [query, setQuery] = useState('');
  const visibleUsers = users.filter((user) => `${user.name} ${user.username} ${user.email}`.toLowerCase().includes(query.toLowerCase()));

  return <DashboardLayout>
    <Head title="Platform admin" />
    <div className="min-h-screen bg-muted/20">
      <AdminHeader />
      <main className="relative mx-auto max-w-7xl space-y-7 px-4 py-7 sm:px-6 lg:px-8">
        <div className="pointer-events-none absolute inset-x-0 top-0 -z-0 h-80 overflow-hidden opacity-70 mask-[linear-gradient(to_bottom,black,transparent)]"><div className="absolute -top-24 left-1/4 size-80 rounded-full bg-primary/10 blur-3xl" /><div className="absolute -top-28 right-1/4 size-72 rounded-full bg-violet-500/10 blur-3xl" /></div>
        <section className="relative z-10 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total users" value={metrics.users} note="Registered accounts" icon={Users} /><MetricCard label="Active wikis" value={metrics.mods} note="Across the platform" icon={LayoutDashboard} /><MetricCard label="API keys" value={metrics.api_keys} note="Issued credentials" icon={KeyRound} /><MetricCard label="Requests today" value={metrics.requests_today} note="All API endpoints" icon={Activity} accent /></section>
        <section className="relative z-10 grid gap-7 xl:grid-cols-[minmax(0,1.45fr)_minmax(360px,0.85fr)]">
          <Card className="overflow-hidden border-border/70 shadow-sm"><CardHeader className="border-b bg-card/70 px-5 py-4 sm:px-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Users & access</CardTitle><p className="mt-1 text-sm text-muted-foreground">Manage platform permissions and account status.</p></div><div className="relative w-full sm:w-52"><Search className="absolute top-1/2 left-2.5 size-3.5 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search users" className="h-8 pl-8 text-xs" /></div></div></CardHeader><CardContent className="p-0"><div className="divide-y">{visibleUsers.map((user) => <UserRow key={user.id} user={user} />)}{visibleUsers.length === 0 && <EmptyState text="No users match your search." />}</div></CardContent></Card>
          <Card className="overflow-hidden border-border/70 shadow-sm"><CardHeader className="border-b bg-card/70 px-5 py-4"><div className="flex items-start justify-between gap-4"><div><CardTitle>API keys</CardTitle><p className="mt-1 text-sm text-muted-foreground">Issued credentials across the platform.</p></div><div className="rounded-lg bg-primary/10 p-2 text-primary"><KeyRound className="size-4" /></div></div></CardHeader><CardContent className="p-0"><div className="divide-y">{keys.map((key) => <KeyRow key={key.id} apiKey={key} />)}{keys.length === 0 && <EmptyState text="No API keys have been issued." />}</div></CardContent></Card>
        </section>
        <section className="relative z-10 space-y-3"><SectionHeading eyebrow="Content operations" title="Latest wikis" description="Platform-wide content overview and ownership." action={<Button asChild variant="outline" size="sm" className="gap-1.5"><Link href="/mods">View directory <ArrowUpRight className="size-3.5" /></Link></Button>} /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{mods.map((mod) => <ModCard key={mod.id} mod={mod} />)}</div></section>
        <section className="relative z-10 grid gap-7 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,0.85fr)]">
          <Card className="overflow-hidden border-border/70 shadow-sm"><CardHeader className="flex-row items-center justify-between border-b bg-card/70 px-5 py-4 sm:px-6"><div><CardTitle>Recent API activity</CardTitle><p className="mt-1 text-sm text-muted-foreground">A live view of platform traffic.</p></div><Button variant="outline" size="sm" className="hidden gap-1.5 sm:flex"><SlidersHorizontal className="size-3.5" /> Filters</Button></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b bg-muted/20 text-[11px] uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3 font-medium sm:px-6">Request</th><th className="px-4 py-3 font-medium">User</th><th className="px-4 py-3 font-medium">Status</th><th className="px-5 py-3 text-right font-medium sm:px-6">When</th></tr></thead><tbody className="divide-y">{activity.map((item) => <tr key={item.id} className="transition-colors hover:bg-muted/20"><td className="px-5 py-4 sm:px-6"><div className="flex items-center gap-2"><Badge variant="outline" className="font-mono text-[10px]">{item.method}</Badge><code className="text-xs">{item.path}</code></div></td><td className="px-4 py-4 text-muted-foreground">{item.user}</td><td className="px-4 py-4"><span className={cn('inline-flex items-center gap-1.5 text-xs font-medium', item.status_code < 400 ? 'text-emerald-600' : 'text-red-600')}><span className={cn('size-1.5 rounded-full', item.status_code < 400 ? 'bg-emerald-500' : 'bg-red-500')} />{item.status_code}</span></td><td className="px-5 py-4 text-right text-xs text-muted-foreground sm:px-6">{item.created_at}</td></tr>)}</tbody></table>{activity.length === 0 && <EmptyState text="No API activity recorded yet." />}</div></CardContent></Card>
          <Card className="border-amber-500/25 bg-amber-500/[0.04] shadow-sm"><CardHeader className="px-5 py-4"><div className="flex items-center gap-2 text-amber-700 dark:text-amber-400"><ShieldCheck className="size-4" /><CardTitle>Admin safety</CardTitle></div></CardHeader><CardContent className="space-y-4 px-5 pb-5 text-sm text-muted-foreground"><p>Changes here affect the entire platform. Every access change is recorded for review.</p><div className="flex items-start gap-3 rounded-lg border border-amber-500/20 bg-background/70 p-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600" /><span>Two-factor authentication is recommended for all platform admins.</span></div><Button variant="outline" size="sm" className="w-full gap-1.5 bg-background/70">Review audit log <ChevronRight className="size-3.5" /></Button></CardContent></Card>
        </section>
      </main>
    </div>
  </DashboardLayout>;
}

function AdminHeader() { return <header className="relative overflow-hidden border-b bg-background"><div className="absolute inset-0 bg-linear-to-r from-primary/[0.07] via-transparent to-violet-500/[0.06]" /><div className="relative mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><div className="mb-5 flex items-center gap-1.5 text-xs text-muted-foreground"><Link href="/dashboard" className="hover:text-foreground">Dashboard</Link><ChevronRight className="size-3" /><span className="text-foreground">Administration</span></div><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary"><ShieldCheck className="size-3.5" /> Platform control</div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Admin dashboard</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground sm:text-base">A clear view of your platform, access, and content health.</p></div><Badge variant="outline" className="gap-2 rounded-full bg-background/70 px-3 py-1.5 text-xs"><span className="size-1.5 rounded-full bg-emerald-500 shadow-[0_0_0_3px] shadow-emerald-500/15" /> All systems operational</Badge></div></div></header>; }
function SectionHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action: React.ReactNode }) { return <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="mb-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h2 className="text-xl font-semibold tracking-tight">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{action}</div>; }
function MetricCard({ label, value, note, icon: Icon, accent = false }: { label: string; value: number; note: string; icon: LucideIcon; accent?: boolean }) { return <Card className="group border-border/70 bg-card/80 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><CardContent className="flex items-start justify-between p-5"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value.toLocaleString()}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div><div className={cn('rounded-xl p-2.5 transition-transform group-hover:scale-105', accent ? 'bg-emerald-500/10 text-emerald-600' : 'bg-primary/10 text-primary')}><Icon className="size-5" /></div></CardContent></Card>; }
function UserRow({ user }: { user: AdminUser }) { return <div className="flex items-center gap-3 px-5 py-3.5 transition-colors hover:bg-muted/20 sm:px-6"><img src={user.avatar} alt="" className="size-9 rounded-full ring-2 ring-background" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{user.name}{user.is_admin && <Badge className="ml-1.5 rounded-full px-1.5 py-0 text-[10px]" variant="secondary">Admin</Badge>}</p><p className="truncate text-xs text-muted-foreground">@{user.username} <span className="mx-1">·</span> {user.owned_mods_count} wikis <span className="mx-1">·</span> {user.api_keys_count} keys</p></div>{user.is_suspended && <Badge variant="destructive" className="hidden sm:inline-flex">Suspended</Badge>}<Button variant="ghost" size="icon" className="size-8" title={user.is_suspended ? 'Reactivate user' : 'Suspend user'} onClick={() => router.patch(`/dashboard/admin/users/${user.id}/suspension`)}><Ban className="size-3.5" /></Button><Button variant="ghost" size="icon" className="size-8" title="Toggle admin access" onClick={() => router.patch(`/dashboard/admin/users/${user.id}/admin`)}><MoreHorizontal className="size-3.5" /></Button></div>; }
function KeyRow({ apiKey }: { apiKey: ApiKey }) { return <div className="px-5 py-4 transition-colors hover:bg-muted/20 sm:px-6"><div className="flex items-center gap-3"><div className="rounded-lg bg-muted p-2"><KeyRound className="size-3.5 text-muted-foreground" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{apiKey.name}</p><p className="font-mono text-[11px] text-muted-foreground">{apiKey.prefix}</p></div><Button variant="ghost" size="icon" className="size-8" title="Copy key prefix" onClick={() => navigator.clipboard?.writeText(apiKey.prefix)}><Copy className="size-3.5" /></Button><Button variant="ghost" size="icon" className="size-8" title="Revoke key" onClick={() => router.delete(`/dashboard/admin/api-keys/${apiKey.id}`)}><Ban className="size-3.5 text-destructive" /></Button></div><div className="mt-2 pl-11 text-xs text-muted-foreground">{apiKey.user}<span className="mx-1">·</span>{apiKey.last_used_at ?? 'Never used'}</div></div>; }
function ModCard({ mod }: { mod: AdminMod }) { return <Card className="group border-border/70 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><CardContent className="p-5"><div className="flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-sm font-semibold text-primary">{mod.name.slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><Link href={`/mod/${mod.slug}`} className="truncate font-medium hover:underline">{mod.name}</Link>{mod.is_suspended ? <Badge variant="destructive" className="rounded-full text-[10px]">Suspended</Badge> : <ExternalLink className="size-3.5 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" />}</div><p className="mt-1 text-xs text-muted-foreground">Owned by {mod.owner} <span className="mx-1">·</span> {mod.pages_count} pages</p></div></div><div className="mt-4 rounded-lg bg-muted/40 p-3"><p className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Recent activity</p>{mod.activity.length ? mod.activity.slice(0, 2).map((item) => <p key={`${mod.id}-${item.title}`} className="truncate text-xs">{item.title} <span className="text-muted-foreground">· {item.updated_at}</span></p>) : <p className="text-xs text-muted-foreground">No recent page updates</p>}</div><div className="mt-4 flex gap-2"><Button variant="outline" size="sm" className="h-8 flex-1 text-xs" onClick={() => router.patch(`/dashboard/admin/mods/${mod.id}/suspension`)}>{mod.is_suspended ? 'Reactivate mod' : 'Suspend mod'}</Button>{mod.github_connected && <Button variant="outline" size="sm" className="h-8 gap-1.5 text-xs" onClick={() => router.post(`/dashboard/admin/mods/${mod.id}/sync`)}><Github className="size-3.5" /> Sync</Button>}</div></CardContent></Card>; }
function EmptyState({ text }: { text: string }) { return <div className="px-6 py-10 text-center text-sm text-muted-foreground">{text}</div>; }
